### ISSUE TITLE
The "Past Test" questions in the Time of Test modal should be auto-filled based on data in the app

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-data-input-client#100]
As a user, I want the app to remember when a person's last test was, and auto-fill the date, type, and result of the most recent prior test.

- [ ] If the person has a prior test logged in the app, display that info and ask if this is the most recent test
![Screen Shot 2020-11-23 at 1 06 23 PM](https://user-images.githubusercontent.com/60664222/99998497-c349d800-2d8c-11eb-91f8-1d584d6d991f.png)

- [ ] If NO (i.e. they got a test at another facility more recently), display the past test questions.
![Screen Shot 2020-11-23 at 1 07 38 PM](https://user-images.githubusercontent.com/60664222/99998581-e70d1e00-2d8c-11eb-89c3-9556b02fec68.png)

- [ ] If the app cannot find a past test logged in the system, ask if it is the person's first test
![Screen Shot 2020-11-23 at 1 08 14 PM](https://user-images.githubusercontent.com/60664222/99998616-f7bd9400-2d8c-11eb-829b-88d5cc9dba12.png)

- [ ] If NO (i.e. they have had a COVID test before, just not logged in this app), display the past test questions
![Screen Shot 2020-11-23 at 1 08 52 PM](https://user-images.githubusercontent.com/60664222/99998690-10c64500-2d8d-11eb-9d99-a60b4b468473.png)

**Comment by willusds** [comment]
Related to #101

**Comment by willusds** [comment]
Date is a tricky part, try to follow USWDS!

**Comment by dmethvin-gov** [comment]
@hmyers-cms The wording "Was this your most recent test", the persona using the app isn't the patient is it? Are you still good with the phrasing in the ticket or should we switch to something like "Is this the most recent test for John Q. Smith?"

**Comment by hmyers-cms** [comment]
That's fine, we do the symptoms question in the same way—it's written so that the user can read the question out loud to the patient

**Comment by dmethvin-gov** [comment]
Done
