### ISSUE TITLE
Update the Time of Test questions modal to match the design

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-data-input-client#101]
- [x] The Past test questions should hide if someone says "Yes" to the "first test?" question (the same way symptoms hide if you say "no symptoms"

- [ ] The date of most recent prior test should be a single input box, which auto-formats as you type. Example of desired behavior: https://codepen.io/tutsplus/pen/KMWqRr

![image](https://user-images.githubusercontent.com/60664222/99446017-6661a400-28ec-11eb-914c-de4c3e605208.png)

**Comment by TomNUSDS** [comment]
Pregnancy has gone from a boolean [yes/no] to a [yes/no/would not state].

<img width="249" alt="Screen Shot 2020-11-20 at 2 08 17 PM" src="https://user-images.githubusercontent.com/74203452/99854650-0ceeb480-2b3a-11eb-992e-ab6033391bd4.png">

Would we want the Past Test to be [yes/no/unknown] as well?

**Comment by benwarfield-usds** [comment]
The pregnancy third choice was an ad lib on my part--designs had yes/no but the output coding had three choices.

**Comment by aliciabeckett-gov** [comment]
This is a dupe with #100
