### ISSUE TITLE
Frontend should extract Okta access token from URl

### ISSUE THREAD

**Issue by nickrobison-usds** [CDCgov/prime-data-input-client#127]
When Okta authenticates a user, it redirects to the given URL with the id and access tokens encoded as hash fragments, details [here](https://prime-eval.okta.com/oauth2/default/v1/authorize?client_id=0oa53ln2xltKTIOyF4h6&response_type=token&scope=openid&redirect_uri=http://localhost:8080/login&nonce=none&state=test).

Once we have this token, we'll need to pass it as a Bearer token to the API.

I've set it up to pass along the users name and email address, but any additional claims can be included as well, just let me know what you need.

- [x] Extract had params for auth and pass to backend

**Comment by timothybest-usds** [comment]
This is complete and working in prod
