### ISSUE TITLE
Test queue allows multiple entries for the same patient.

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-data-input-client#151]
In the in-memory prototype, we were unable to add a patient to the queue twice. Now, we are trivially able to.

Fix steps:

- [x] patch API code to check for this condition and throw an exception if it occurs
- [x] add a partial index to the DB to prevent this from being possible even with race conditions in the API
- [x] update the UI to detect that this is about to happen, and don't send that request in the first place.

**Comment by dmethvin-gov** [comment]
I'll take the UI portion of this, which is a side effect of #154. I assigned Ben for the backend since he's already ticked a box.

**Comment by willusds** [comment]
@benwarfield-usds working on the fix, reporting dual users

**Comment by benwarfield-usds** [comment]
@timothybest-usds should we tick the third box and close this now?

**Comment by timothybest-usds** [comment]
https://github.com/CDCgov/prime-data-input-client/pull/203 solves the UI issue. Box ticked
