### ISSUE TITLE
wire simplereport.cdc.gov to prod env

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-data-input-client#160]
blocked on CDC

**Comment by pete-usds** [comment]
Task tracking: This should "just work" on HTTP when the domain is pointed at the right IP.

However, we'll need to generate an SSL certificate and add it to the application gateway for HTTPS, and probably configure a static redirect. This "shouldn't take too long" but that's the manual task for after the DNS name is added.

**Comment by pete-usds** [comment]
This was completed last Wed! Wee.
