### ISSUE TITLE
Customize Okta log in page

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-data-input-client#243]
We learned from on-site research that users are confused by the Okta sign-in flow. Specifically, we saw that users did not know to sign in at simplereport.cdc.gov. They do not receive any guidance after creating their accounts to sign in at simplereport.cdc.gov. Simple Report is also not an application they can look up within the Okta applications page.

Consider:
- Customizing Okta landing page to at a minimum show a SimpleReport logo instead of the Okta one, so that users know what they are logging into. Ideally we can fully customize to match the look of the rest of the app, but open to a discussion about LOE
- Sending users a welcome email after Okta set up
- Adding SImpleReport to the list of Okta apps

Alicia to connect with Kam to figure out what's possible from an Okta front.

**Comment by willusds** [comment]
@willusds Merge with #258
