### ISSUE TITLE
People Tab: Days since last test doesn't work

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-data-input-client#252]
On the People tab, days since last test says 'N/A' for everyone, even if they have been tested. We should put in how many days since the person has been tested.

Tested today = 0 days
Tested yesterday = 1 day
and so forth

See screenshot below
<img width="1057" alt="Screen Shot 2020-12-07 at 3 45 48 PM" src="https://user-images.githubusercontent.com/50637336/101418796-780ee980-38a3-11eb-8068-657420258c8b.png">

**Comment by willusds** [comment]
Fixed, doesn't exist anymore!

**Comment by aliciabeckett-gov** [comment]
I think we got this wrong. It's fixed in the Results tab, still very much a problem in the People tab.
