### ISSUE TITLE
Result of Previous Tests should not default to 'positive'

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-data-input-client#269]
Test type and test result should default to "Select an Option" rather than defaulting to a valid option. That way a user either is not selecting an option, or is clearly selecting an option, but not accidentally selecting an incorrect option.

<img width="657" alt="Screen Shot 2020-12-09 at 8 27 10 AM" src="https://user-images.githubusercontent.com/50637336/101667967-d2738b80-3a04-11eb-9716-949c476ec6dc.png">

@katiealoisi @hmyers-cms FYI

**Comment by hmyers-cms** [comment]
I already covered this in this ticket: https://github.com/CDCgov/prime-central/issues/176

**Comment by sharmaneil** [comment]
Done and merged. Also fixed some of the style issues and a few other bugs while I was in that part of the codebase.

**Comment by dmethvin-gov** [comment]
Closing since it's done.
