### ISSUE TITLE
Minor test queue persistence bugs

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-data-input-client#60]
Hoisted from #59 

- [ ] * device selection and test result are not persisted to redux unless AoE questions are saved
- [x] * tests can be submitted with no result

**Comment by benwarfield-usds** [comment]
@hmyers-cms is the second checkbox worth trying to make happen as a minor usability enhancement, or should we just close this out?

**Comment by timothybest-usds** [comment]
Closing this ticket as this data is now persisted to the postrges DB not redux
