### ISSUE TITLE
CSV Upload

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-data-input-client#73]
(built out after database table exists)
- [ ] Create endpoint to support csv upload with these fields:
        patientID,
        patientLastName,
        patientFirstName,
        patientMiddleName,
        patientSuffix,
        patientRace,
        patientDOB,
        patientGender,
        patientEthnicity,
        patientStreet,
        patientStreet2,
        patientCity,
        patientCounty,
        patientState,
        patientZipCode,
        patientPhoneNumber,
        patientEmail,
        patientAge,
        employedInHealthcare,
        typeOfHealthcareProfessional,
        residentCongregateSetting,
        patientResidencyType,

**Comment by willusds** [comment]
(Not necessary for MVP)

**Comment by benwarfield-usds** [comment]
Was this resolved by #147?

**Comment by timothybest-usds** [comment]
implemented in #147
