### ISSUE TITLE
Get the app using dummy endpoints

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-data-input-client#74]
**Feature needs:**
- [ ] Displaying the queue 
- [ ] Add data
- [ ] Update data
- [ ] Delete data
- [ ] Submit data
- [ ] Update organization information
- [ ] Load organization information
- [ ] Add device
- [ ] Remove device
- [ ] Set default device
- [ ] Load devices
- [ ] Load person
- [ ] Add person
- [ ] Update person
- [ ] Reading results (tab)
- [ ] Add person to queue
- [ ] Remove person from queue
- [ ] Load queue
- [ ] Update device
- [ ] Time of test questions
- [ ] Clear results
- [ ] Settings (organization data)

Blocked by #73

**Comment by sharmaneil** [comment]
Grouped for better understanding

####Queue
- [ ] Displaying the queue 
- [ ] Add patient to queue
- [ ] Remove patient from queue
- [ ] Submit from queue
- [ ] Update patient in queue (with AOE Questionaire)

#### Settings
- [ ] Update organization information
- [ ] Load organization information
- [ ] Add device
- [ ] Remove device
- [ ] Set default device
- [ ] Load devices

#### People
- [ ] Get all people
- [ ] Add a single person
- [ ] Update a single person
- [ ] Bulk upload a bunch of people from the CSV

#### Results
- [ ] Reading results (tab)
- [ ] Time of test questions
- [ ] Clear results (@willusds what does this mean?)

**Comment by willusds** [comment]
@sharmaneil Sure, that looks good. I believe the clear results was to just zero out if you'd done a search and wanted to move to a different part of the app. @timothybest-usds is that correct?

**Comment by timothybest-usds** [comment]
that is my understanding. For this ticket it will be done when the app works the same with the dummy backend as with local storage. the list is to hopefully make it easier to track everything

**Comment by aliciabeckett-gov** [comment]
Clear results was for in the testing queue, if a user selects a result (like positive or negative) and wants to clear the result. However, if we are not saving selected results to the backend we don't need clear results. We can add it later.

**Comment by aliciabeckett-gov** [comment]
Priorities:

1. Queue- everything
2. Results
3. People- display on people page  - get all people
4. People - Add a single person & Update a single person
5. Settings - Load organization information
6. Settings - Load Devices
7. Settings - Update organization information
8. Settings - Update Devices
9. People - Bulk upload a bunch of people from the CSV

@sharmaneil @timothybest-usds - FYI

**Comment by benwarfield-usds** [comment]
For what it's worth, it's hard to do much with the queue without having a people list first. :-)

**Comment by benwarfield-usds** [comment]
This issue has been overtaken by events.
