### ISSUE TITLE
Save results in queue that are not submitted

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-data-input-client#75]
### Backend:
- [x] on `TestOrder` creation the device should be set to the organization's default device
- [x] create mutation `editPatientInQueue` it should behave like `addTestResult()` but should not create a `TestEvent` and should not add a value to `dateTested`
```
editPatientInQueue(
   patientId: String!
   deviceId: String,
   result: String
)          
```

### Frontend:
- [x] When a user clicks positive/negative/inconclusive, it should call `editPatientInQueue()` to save this to the pending test order object.
- [x] When a user a device, it should call `editPatientInQueue()` to save this to the pending test order object.
- [x] Submit should still call `addTestResult` but not pass the result and device

**Comment by benwarfield-usds** [comment]
The selection of the test device probably also should be included in this, per #60 (which should probably be closed in favor of this).

**Comment by dmethvin-gov** [comment]
Also related to https://github.com/CDCgov/prime-central/issues/151 ; the queue entry doesn't have a device id so it assigns whatever the current default device is. Since there is no way for the user to persist the device (see #60) it always gets the default.

**Comment by benwarfield-usds** [comment]
An implication of this that I hadn't noticed: is it mandatory for an organization to have a default device type?

Or, put another way, is it acceptable to make an organization having a default device type a prerequisite for users in that organization being able to add patients to their test queue?

**Comment by dmethvin-gov** [comment]
Good question about the default device type. The device list we show in the queue has a "-Select-" at the top so at least from a program standpoint we could let them get that far without choosing the device. I suppose if a facility had 3 different active devices in use they might want to make people choose manually to reduce the chance of the wrong device being selected by default. However we don't have any front-end validation at the moment to ensure that they actually choose a device before submitting the result, which seems bad.

**Comment by benwarfield-usds** [comment]
I don't think we can safely remove the device and result arguments from the save-test action: there is a race condition that can be trivially produced by having two users have access to the queue, in which the person who hits "submit" is looking at a stale version of the test order, and submits something other than what they thought they submitted.
