### ISSUE TITLE
Auto Fill the Past Test Questions in Time of Test questions

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-data-input-client#87]
Per usability feedback, we should update the "Last Test" question in the time of test questions to:

- [ ] Auto-fill the response with the last test the person had through SimpleReport
- [ ] If it's the users first test hide the other questions (date of last test, kind of test, result)

**Comment by timothybest-usds** [comment]
closing in favor of https://github.com/CDCgov/prime-data-input-client/issues/100
